### ISSUE TITLE
Not hilited fully

### ISSUE THREAD

**Issue by Alexey-T** [calculuswhiz/SHARC-assembly-Sublime-Syntax#1]
Not all words are hilited: toggle, cntr, ena

File SHARC:
[Blink.zip](https://github.com/calculuswhiz/SHARC-assembly-Sublime-Syntax/files/629878/Blink.zip)

**Comment by calculuswhiz** [comment]
I can't find any documentation on these keywords anywhere. Can you provide it?
I'm looking at the [instruction set reference](http://smd.hu/Data/Analog/DSP/SHARC/ADSP-21065%20Users%20Manual%20&%20Tech.Reference/mz_apa.pdf), and I'm not seeing any of them.

**Comment by Alexey-T** [comment]
This pdf is about ADSP-2nnnn, and my file seems for other ADSP-mmmm series.

**Comment by calculuswhiz** [comment]
I mean, I'd like to help, but I really can't find anything on it. If you can find the documentation, or point me to where I can find it, that would be super great. I also don't have access to the computer lab with all the software anymore.

(To be honest, I really don't know much about DSP or SHARC. This was a side project I came up with a couple years ago.)

**Comment by Alexey-T** [comment]
ok. It is page http://www.analog.com/en/design-center/processors-and-dsp/adsp-218x-219x-code-examples.html
ADSP 218x. file Timer (zip). has "toggle" commd.

**Comment by Alexey-T** [comment]
http://www.analog.com/media/en/dsp-documentation/processor-manuals/5876423468xinset.pdf
